const vars = {
  formats: {
    VIDEO: ["video/mp4", "video/oog", "video/webm"],
    AUDIO: [ "audio/mp3", "audio/oog"],
    PHOTO: ["image/gif", "image/png", "image/jpg", "image/jpeg", "image/webp"]
  },
  MainStream: ["Twitter", "TikTok", "Facebook", "Intagram", "Pintrest", "None", "N/A"],
  lorem: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Habitant morbi tristique senectus et. Urna duis convallis convallis tellus id interdum. Ultricies tristique nulla aliquet enim tortor at auctor urna. Sit amet est placerat in egestas. Imperdiet massa tincidunt nunc pulvinar. At risus viverra adipiscing at in tellus. Pellentesque id nibh tortor id aliquet lectus. Congue eu consequat ac felis donec. Iaculis urna id volutpat lacus laoreet non curabitur gravida.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Habitant morbi tristique senectus et. Urna duis convallis convallis tellus id interdum. Ultricies tristique nulla aliquet enim tortor at auctor urna. Sit amet est placerat in egestas. Imperdiet massa tincidunt nunc pulvinar. At risus viverra adipiscing at in tellus. Pellentesque id nibh tortor id aliquet lectus. Congue eu consequat ac felis donec. Iaculis urna id volutpat lacus laoreet non curabitur gravida.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Habitant morbi tristique senectus et. Urna duis convallis convallis tellus id interdum. Ultricies tristique nulla aliquet enim tortor at auctor urna. Sit amet est placerat in egestas. Imperdiet massa tincidunt nunc pulvinar. At risus viverra adipiscing at in tellus. Pellentesque id nibh tortor id aliquet lectus. Congue eu consequat ac felis donec. Iaculis urna id volutpat lacus laoreet non curabitur gravida.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Habitant morbi tristique senectus et. Urna duis convallis convallis tellus id interdum. Ultricies tristique nulla aliquet enim tortor at auctor urna. Sit amet est placerat in egestas. Imperdiet massa tincidunt nunc pulvinar. At risus viverra adipiscing at in tellus. Pellentesque id nibh tortor id aliquet lectus. Congue eu consequat ac felis donec. Iaculis urna id volutpat lacus laoreet non curabitur gravida.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Habitant morbi tristique senectus et. Urna duis convallis convallis tellus id interdum. Ultricies tristique nulla aliquet enim tortor at auctor urna. Sit amet est placerat in egestas. Imperdiet massa tincidunt nunc pulvinar. At risus viverra adipiscing at in tellus. Pellentesque id nibh tortor id aliquet lectus. Congue eu consequat ac felis donec. Iaculis urna id volutpat lacus laoreet non curabitur gravida",
  apiURL: process.env.REACT_APP_NODE_ENV === 'local' ? 'http://localhost:9000': 'https://house-of-memes.herokuapp.com'
};

export default vars;
